### ISSUE TITLE
Brak obrazka w sekcji dodatki

### ISSUE THREAD

**Issue by hobforkerCDV** [hobdevCDV/pizzeriaCDV#7]
Cześć, zauważyłem, że w sekcji z dodatkami brakuje obrazka! Zdaje się, że trzeba to poprawić.

**Comment by hobdevCDV** [comment]
commit 52b16d70531eb1c4392cd906bfb4d8054fcd2f82 naprawia ten błąd

**Comment by hobdevCDV** [comment]
52b16d70531eb1c4392cd906bfb4d8054fcd2f82 fixes #7

**Comment by hobdevCDV** [comment]
52b16d70531eb1c4392cd906bfb4d8054fcd2f82 Closes #7
